#for testing purpose
#set_property IOSTANDARD LVCMOS33 [get_ports {distance[15]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {distance[14]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {distance[13]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {distance[12]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {distance[11]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {distance[10]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {distance[9]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {distance[8]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {distance[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {distance[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {distance[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {distance[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {distance[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {distance[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {distance[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {distance[0]}]
#set_property PACKAGE_PIN L1 [get_ports {distance[15]}]
#set_property PACKAGE_PIN P1 [get_ports {distance[14]}]
#set_property PACKAGE_PIN N3 [get_ports {distance[13]}]
#set_property PACKAGE_PIN P3 [get_ports {distance[12]}]
#set_property PACKAGE_PIN U3 [get_ports {distance[11]}]
#set_property PACKAGE_PIN W3 [get_ports {distance[10]}]
#set_property PACKAGE_PIN V3 [get_ports {distance[9]}]
#set_property PACKAGE_PIN V13 [get_ports {distance[8]}]
#set_property PACKAGE_PIN V14 [get_ports {distance[7]}]
#set_property PACKAGE_PIN U14 [get_ports {distance[6]}]
#set_property PACKAGE_PIN U15 [get_ports {distance[5]}]
#set_property PACKAGE_PIN W18 [get_ports {distance[4]}]
#set_property PACKAGE_PIN V19 [get_ports {distance[3]}]
#set_property PACKAGE_PIN U19 [get_ports {distance[2]}]
#set_property PACKAGE_PIN E19 [get_ports {distance[1]}]
#set_property PACKAGE_PIN U16 [get_ports {distance[0]}]

set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN V17 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports sig]
set_property PACKAGE_PIN K17 [get_ports sig]

set_property PACKAGE_PIN A14 [get_ports A]
set_property IOSTANDARD LVCMOS33 [get_ports A]

set_property PACKAGE_PIN B15 [get_ports B]
set_property IOSTANDARD LVCMOS33 [get_ports B]

set_property PACKAGE_PIN A16 [get_ports Ab]
set_property IOSTANDARD LVCMOS33 [get_ports Ab]

set_property PACKAGE_PIN B16 [get_ports Bb]
set_property IOSTANDARD LVCMOS33 [get_ports Bb]

set_property PACKAGE_PIN W7 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property PACKAGE_PIN W6 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property PACKAGE_PIN U8 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property PACKAGE_PIN V8 [get_ports d]
set_property IOSTANDARD LVCMOS33 [get_ports d]
set_property PACKAGE_PIN V7 [get_ports DP]
set_property IOSTANDARD LVCMOS33 [get_ports DP]
set_property PACKAGE_PIN U5 [get_ports e]
set_property IOSTANDARD LVCMOS33 [get_ports e]
set_property PACKAGE_PIN V5 [get_ports f]
set_property IOSTANDARD LVCMOS33 [get_ports f]
set_property PACKAGE_PIN U7 [get_ports g]
set_property IOSTANDARD LVCMOS33 [get_ports g]
set_property PACKAGE_PIN W4 [get_ports {an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property PACKAGE_PIN U2 [get_ports {an[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
