# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Vivado_Projects/Ultrasonic/Ultrasonic.cache/wt [current_project]
set_property parent.project_path E:/Vivado_Projects/Ultrasonic/Ultrasonic.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo e:/Vivado_Projects/Ultrasonic/Ultrasonic.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  E:/Vivado_Projects/Ultrasonic/Ultrasonic.srcs/sources_1/new/SevSeg_4digit.sv
  E:/Vivado_Projects/Ultrasonic/Ultrasonic.srcs/sources_1/new/Motor.sv
  E:/Vivado_Projects/Ultrasonic/Ultrasonic.srcs/sources_1/new/UltrasonicDriver.sv
  E:/Vivado_Projects/Ultrasonic/Ultrasonic.srcs/sources_1/new/AutoBreakSystem.sv
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Vivado_Projects/Ultrasonic/Ultrasonic.srcs/constrs_1/new/constraint.xdc
set_property used_in_implementation false [get_files E:/Vivado_Projects/Ultrasonic/Ultrasonic.srcs/constrs_1/new/constraint.xdc]


synth_design -top AutoBreakSystem -part xc7a35tcpg236-1


write_checkpoint -force -noxdef AutoBreakSystem.dcp

catch { report_utilization -file AutoBreakSystem_utilization_synth.rpt -pb AutoBreakSystem_utilization_synth.pb }
